"""Target Attention Analysis and XAI for Drug-Target Interaction (DTI).

Extracts and visualizes residue-level binding contributions from bidirectional Cross-Attention
or Pocket-Guided Attention weights:
1. Identifies Top 10 key binding residues dominating interaction affinity.
2. Supports coordinate re-mapping (e.g., pocket-sliced indices back to full UniProt sequence).
3. Produces interaction heatmap matrices and percentage contribution distributions.
4. Generates PyMOL scripts (.pml) with B-factor spectrum coloring for 3D structural inspection.
"""

import json
import logging
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import numpy as np

logger = logging.getLogger("tdc_studio.features.target_attention")

AA_1TO3 = {
    "A": "Ala", "R": "Arg", "N": "Asn", "D": "Asp", "C": "Cys",
    "E": "Glu", "Q": "Gln", "G": "Gly", "H": "His", "I": "Ile",
    "L": "Leu", "K": "Lys", "M": "Met", "F": "Phe", "P": "Pro",
    "S": "Ser", "T": "Thr", "W": "Trp", "Y": "Tyr", "V": "Val",
    "U": "Sec", "O": "Pyl",
}


@dataclass
class ResidueContribution:
    """Detailed attribution metrics for an individual target residue."""
    rank: int
    residue_index: int          # 1-based original sequence coordinate
    residue_name: str           # 1-letter code (e.g. 'M')
    residue_code: str           # 3-letter + index (e.g. 'Met790')
    raw_score: float            # Summed attention weight
    normalized_score: float     # Scaled to [0.0, 1.0] relative to peak residue
    percent_contribution: float # Percentage of total binding attention (%)
    is_in_pocket: bool = True


@dataclass
class TargetAttentionResult:
    """Encapsulates the complete XAI target attention analysis."""
    top_residues: List[ResidueContribution]
    total_residues_analyzed: int
    peak_residue: str
    contact_map: np.ndarray      # [L_drug, L_target/L_pocket]
    residue_scores: np.ndarray   # [L_target/L_pocket]
    coordinate_map: List[int]    # 1-based coordinates for each column
    pymol_command: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert analysis result to JSON-serializable dictionary."""
        return {
            "top_residues": [asdict(r) for r in self.top_residues],
            "total_residues_analyzed": self.total_residues_analyzed,
            "peak_residue": self.peak_residue,
            "coordinate_map": self.coordinate_map,
            "pymol_command": self.pymol_command,
        }

    def export_pymol_script(
        self,
        output_path: Union[str, Path],
        pdb_file: Optional[str] = None,
        selection_name: str = "dti_hotspot",
    ) -> str:
        """Write a comprehensive PyMOL script (.pml) for 3D visual inspection.

        Args:
            output_path: Target path to save .pml script.
            pdb_file: Optional path or PDB code to load.
            selection_name: Name of PyMOL selection object.

        Returns:
            The written PyMOL script text.
        """
        lines = [
            f"# PyMOL Visualization Script generated by TDC-Studio TargetAttention",
            f"# Total residues analyzed: {self.total_residues_analyzed} | Peak: {self.peak_residue}",
            "reinitialize",
        ]
        if pdb_file:
            lines.append(f"load {pdb_file}, target_protein")
            lines.append("hide everything, target_protein")
            lines.append("show cartoon, target_protein")
            lines.append("color gray80, target_protein")

        # Top 10 stick selection
        top_res_nums = [str(r.residue_index) for r in self.top_residues]
        if top_res_nums:
            resi_expr = "+".join(top_res_nums)
            lines.extend([
                f"select {selection_name}, resi {resi_expr}",
                f"show sticks, {selection_name}",
                f"color yellow, {selection_name}",
                f"show nb_spheres, {selection_name}",
                f"zoom {selection_name}, 8.0",
            ])

        # High-intensity top 3 highlight in magenta
        if len(self.top_residues) >= 3:
            top3_nums = "+".join([str(r.residue_index) for r in self.top_residues[:3]])
            lines.extend([
                f"select {selection_name}_top3, resi {top33} " if (top33 := top3_nums) else "",
                f"color magenta, {selection_name}_top3",
                f"label {selection_name}_top3 and name CA, f'%s%s' % (resn, resi)",
            ])

        script_text = "\n".join(line for line in lines if line)
        Path(output_path).write_text(script_text, encoding="utf-8")
        return script_text


class TargetAttentionAnalyzer:
    """Analyzer extracting residue-level binding contributions from attention weights."""

    def __init__(self, top_k: int = 10):
        self.top_k = top_k

    def analyze(
        self,
        contact_map: np.ndarray,
        target_seq: str,
        coordinate_map: Optional[List[int]] = None,
        pocket_indices: Optional[List[int]] = None,
    ) -> TargetAttentionResult:
        """Analyze cross-attention contact map to rank target residues.

        Args:
            contact_map: 2D numpy array [L_drug, L_target] (or [L_drug, L_pocket]).
            target_seq: Full amino acid sequence string or pocket sub-sequence.
            coordinate_map: Optional 1-based residue coordinate map matching contact_map columns.
            pocket_indices: Optional list of 0-based pocket residue indices.

        Returns:
            TargetAttentionResult containing Top-K residues and PyMOL commands.
        """
        arr = np.asarray(contact_map, dtype=np.float32)
        if arr.ndim != 2:
            raise ValueError(f"contact_map must be 2D, got shape {arr.shape}")

        l_drug, l_target = arr.shape

        # Establish 1-based coordinate mapping
        if coordinate_map is not None:
            actual_coords = list(coordinate_map)
        elif pocket_indices is not None:
            actual_coords = [idx + 1 for idx in pocket_indices]
        else:
            actual_coords = list(range(1, l_target + 1))

        # Clamp length to match contact_map columns
        if len(actual_coords) > l_target:
            actual_coords = actual_coords[:l_target]
        elif len(actual_coords) < l_target:
            # Pad if needed
            start_num = actual_coords[-1] + 1 if actual_coords else 1
            actual_coords.extend(range(start_num, start_num + (l_target - len(actual_coords))))

        # Aggregate attention weights across all drug tokens/atoms
        residue_weights = np.sum(arr, axis=0)  # [L_target]
        total_weight = float(np.sum(residue_weights))
        max_weight = float(np.max(residue_weights)) if len(residue_weights) > 0 else 0.0

        if max_weight > 1e-8:
            norm_scores = residue_weights / max_weight
        else:
            norm_scores = residue_weights.copy()

        # Rank residues descending
        k = min(self.top_k, l_target)
        top_indices = np.argsort(-residue_weights)[:k]

        contributions: List[ResidueContribution] = []
        for rank, col_idx in enumerate(top_indices, start=1):
            c_idx = int(col_idx)
            res_1based = actual_coords[c_idx]

            # Sequence lookup: if target_seq covers the full sequence (res_1based), use it
            if 1 <= res_1based <= len(target_seq):
                res_char = target_seq[res_1based - 1].upper()
            elif c_idx < len(target_seq):
                res_char = target_seq[c_idx].upper()
            else:
                res_char = "X"

            res_3 = AA_1TO3.get(res_char, res_char)
            res_code = f"{res_3}{res_1based}"

            raw_sc = float(residue_weights[c_idx])
            norm_sc = float(norm_scores[c_idx])
            pct = (raw_sc / total_weight * 100.0) if total_weight > 1e-8 else 0.0

            contributions.append(
                ResidueContribution(
                    rank=rank,
                    residue_index=res_1based,
                    residue_name=res_char,
                    residue_code=res_code,
                    raw_score=round(raw_sc, 5),
                    normalized_score=round(norm_sc, 4),
                    percent_contribution=round(pct, 2),
                    is_in_pocket=True,
                )
            )

        peak_res = contributions[0].residue_code if contributions else "None"

        # Generate PyMOL single-line command
        resi_nums = [str(r.residue_index) for r in contributions]
        if resi_nums:
            resi_str = "+".join(resi_nums)
            pymol_cmd = (
                f"select binding_pocket, resi {resi_str}; "
                f"show sticks, binding_pocket; "
                f"color yellow, binding_pocket; "
                f"zoom binding_pocket, 6.0;"
            )
        else:
            pymol_cmd = ""

        return TargetAttentionResult(
            top_residues=contributions,
            total_residues_analyzed=l_target,
            peak_residue=peak_res,
            contact_map=arr,
            residue_scores=residue_weights,
            coordinate_map=actual_coords,
            pymol_command=pymol_cmd,
        )


def analyze_target_attention(
    contact_map: np.ndarray,
    target_seq: str,
    coordinate_map: Optional[List[int]] = None,
    pocket_indices: Optional[List[int]] = None,
    top_k: int = 10,
) -> TargetAttentionResult:
    """Convenience functional wrapper for TargetAttentionAnalyzer."""
    analyzer = TargetAttentionAnalyzer(top_k=top_k)
    return analyzer.analyze(
        contact_map=contact_map,
        target_seq=target_seq,
        coordinate_map=coordinate_map,
        pocket_indices=pocket_indices,
    )
