"""Physiologically-Based Pharmacokinetics (PBPK) Engine.

Provides mechanistic translation of in vitro ADMET predictions into in vivo human PK parameters:
- Systemic Total Clearance (CL_total = (Vdss * ln2) / t_1/2)
- Well-Stirred Hepatic Clearance (CL_H) with IVIVE scaling
- Hepatic Extraction Ratio (E_H) and classification (Low / Intermediate / High)
- Unbound Fraction (f_u) from PPBR
- Elimination rate constant (k_e) and Mean Residence Time (MRT)
- First-Pass Hepatic Bioavailability Upper Bound (F_max)
"""

import math
from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class HumanPhysiologicalParams:
    """Standard physiological parameters for an adult human (70 kg reference)."""

    body_weight_kg: float = 70.0  # Body weight (kg)
    liver_weight_kg: float = 1.8  # Liver weight (kg)
    liver_weight_per_bw_g_kg: float = 25.7  # g liver per kg body weight (1800g / 70kg)
    hepatic_blood_flow_ml_min_kg: float = 20.7  # Hepatic blood flow (mL/min/kg)
    mppgl: float = 45.0  # Microsomal protein per gram of liver (mg/g)
    hpgl: float = 107.0  # Hepatocytes per gram of liver (10^6 cells/g)


@dataclass
class PBPKProfile:
    """Comprehensive in vivo pharmacokinetic profile generated by PBPK engine."""

    smiles: str
    vdss_l_kg: float  # Steady-state volume of distribution (L/kg)
    half_life_hr: float  # Elimination half-life t_1/2 (hours)
    ppbr_percent: float  # Plasma protein binding rate (%)
    unbound_fraction_fu: float  # Fraction unbound in plasma (0.0 ~ 1.0)
    cl_total_l_hr_kg: float  # Total systemic clearance (L/hr/kg)
    cl_total_ml_min_kg: float  # Total systemic clearance (mL/min/kg)
    cl_total_l_hr: float  # Whole-body systemic clearance (L/hr for 70kg)
    ke_hr_inv: float  # Elimination rate constant k_e (1/hr)
    mrt_hr: float  # Mean residence time MRT (hours)
    cl_int_mic_scaled_ml_min_kg: Optional[float] = None  # IVIVE scaled microsome CL_int
    cl_int_hep_scaled_ml_min_kg: Optional[float] = None  # IVIVE scaled hepatocyte CL_int
    cl_hepatic_ml_min_kg: Optional[float] = None  # Well-stirred hepatic clearance (mL/min/kg)
    extraction_ratio_eh: Optional[float] = None  # Hepatic extraction ratio E_H (0.0 ~ 1.0)
    extraction_class: Optional[str] = None  # "Low" (<0.3), "Intermediate" (0.3~0.7), "High" (>0.7)
    f_max_oral: Optional[float] = None  # First-pass hepatic availability limit (1 - E_H)

    def to_dict(self) -> Dict[str, Any]:
        """Convert profile to serializable dictionary."""
        return {
            "smiles": self.smiles,
            "vdss_l_kg": round(self.vdss_l_kg, 4),
            "half_life_hr": round(self.half_life_hr, 3),
            "ppbr_percent": round(self.ppbr_percent, 2),
            "unbound_fraction_fu": round(self.unbound_fraction_fu, 4),
            "cl_total_l_hr_kg": round(self.cl_total_l_hr_kg, 4),
            "cl_total_ml_min_kg": round(self.cl_total_ml_min_kg, 3),
            "cl_total_l_hr_70kg": round(self.cl_total_l_hr, 3),
            "ke_hr_inv": round(self.ke_hr_inv, 4),
            "mrt_hr": round(self.mrt_hr, 3),
            "cl_int_mic_scaled_ml_min_kg": (
                round(self.cl_int_mic_scaled_ml_min_kg, 3)
                if self.cl_int_mic_scaled_ml_min_kg is not None
                else None
            ),
            "cl_int_hep_scaled_ml_min_kg": (
                round(self.cl_int_hep_scaled_ml_min_kg, 3)
                if self.cl_int_hep_scaled_ml_min_kg is not None
                else None
            ),
            "cl_hepatic_ml_min_kg": (
                round(self.cl_hepatic_ml_min_kg, 3)
                if self.cl_hepatic_ml_min_kg is not None
                else None
            ),
            "extraction_ratio_eh": (
                round(self.extraction_ratio_eh, 4) if self.extraction_ratio_eh is not None else None
            ),
            "extraction_class": self.extraction_class,
            "f_max_oral": (round(self.f_max_oral, 4) if self.f_max_oral is not None else None),
        }


class PBPKEngine:
    """Physiologically-Based Pharmacokinetics (PBPK) Simulation and Integration Engine."""

    def __init__(self, phys_params: Optional[HumanPhysiologicalParams] = None):
        self.phys = phys_params or HumanPhysiologicalParams()

    def calculate_profile(
        self,
        smiles: str,
        vdss_l_kg: float,
        half_life_hr: float,
        ppbr_percent: float,
        cl_int_mic_ul_min_mg: Optional[float] = None,
        cl_int_hep_ul_min_10e6cells: Optional[float] = None,
    ) -> PBPKProfile:
        """Calculate complete in vivo pharmacokinetic profile from ADMET predictions.

        Args:
            smiles: Chemical SMILES identifier.
            vdss_l_kg: Steady-state volume of distribution (L/kg).
            half_life_hr: Elimination half-life t_1/2 (hours).
            ppbr_percent: Plasma protein binding rate (%).
            cl_int_mic_ul_min_mg: In vitro microsomal clearance (uL/min/mg protein).
            cl_int_hep_ul_min_10e6cells: In vitro hepatocyte clearance (uL/min/10^6 cells).

        Returns:
            PBPKProfile containing all derived pharmacokinetic metrics.
        """
        # Guard against zero or negative values
        vdss = max(float(vdss_l_kg), 1e-4)
        t_half = max(float(half_life_hr), 1e-4)
        ppbr = min(max(float(ppbr_percent), 0.0), 99.99)

        # 1. Free fraction f_u
        fu = max(1.0 - (ppbr / 100.0), 1e-4)

        # 2. Elimination rate constant k_e and MRT
        ln2 = math.log(2.0)
        ke = ln2 / t_half
        mrt = t_half / ln2

        # 3. Systemic Total Clearance CL_total = (Vdss * ln2) / t_1/2
        # Units: (L/kg) * (1/hr) = L/hr/kg
        cl_total_l_hr_kg = (vdss * ln2) / t_half

        # Convert to mL/min/kg: (L/hr/kg) * (1000 mL / 1 L) / (60 min / 1 hr)
        cl_total_ml_min_kg = cl_total_l_hr_kg * (1000.0 / 60.0)

        # Whole body 70kg clearance (L/hr)
        cl_total_l_hr = cl_total_l_hr_kg * self.phys.body_weight_kg

        # 4. In Vitro to In Vivo Extrapolation (IVIVE)
        cl_int_mic_scaled = None
        if cl_int_mic_ul_min_mg is not None and cl_int_mic_ul_min_mg > 0:
            # uL/min/mg * mg/g * g_liver/kg_BW * (1 mL / 1000 uL) = mL/min/kg
            cl_int_mic_scaled = (
                cl_int_mic_ul_min_mg * self.phys.mppgl * self.phys.liver_weight_per_bw_g_kg / 1000.0
            )

        cl_int_hep_scaled = None
        if cl_int_hep_ul_min_10e6cells is not None and cl_int_hep_ul_min_10e6cells > 0:
            # uL/min/10^6 cells * 10^6 cells/g * g_liver/kg_BW * (1 mL / 1000 uL) = mL/min/kg
            cl_int_hep_scaled = (
                cl_int_hep_ul_min_10e6cells
                * self.phys.hpgl
                * self.phys.liver_weight_per_bw_g_kg
                / 1000.0
            )

        # 5. Well-Stirred Model for Hepatic Clearance
        # Preferred scaled CL_int: hepatocyte if available, else microsome, else derive from systemic
        selected_cl_int = cl_int_hep_scaled or cl_int_mic_scaled

        qh = self.phys.hepatic_blood_flow_ml_min_kg
        cl_h = None
        eh = None
        eh_class = None
        f_max = None

        if selected_cl_int is not None:
            # CL_H = (Q_H * f_u * CL_int) / (Q_H + f_u * CL_int)
            cl_h = (qh * fu * selected_cl_int) / (qh + fu * selected_cl_int)
            eh = min(max(cl_h / qh, 0.0), 1.0)
        else:
            # If in vitro CL_int is not provided, estimate E_H from systemic clearance assuming hepatic elimination
            eh = min(max(cl_total_ml_min_kg / qh, 0.0), 1.0)
            cl_h = min(cl_total_ml_min_kg, qh)

        if eh is not None:
            if eh < 0.30:
                eh_class = "Low"
            elif eh <= 0.70:
                eh_class = "Intermediate"
            else:
                eh_class = "High"
            f_max = max(1.0 - eh, 0.0)

        return PBPKProfile(
            smiles=smiles,
            vdss_l_kg=vdss,
            half_life_hr=t_half,
            ppbr_percent=ppbr,
            unbound_fraction_fu=fu,
            cl_total_l_hr_kg=cl_total_l_hr_kg,
            cl_total_ml_min_kg=cl_total_ml_min_kg,
            cl_total_l_hr=cl_total_l_hr,
            ke_hr_inv=ke,
            mrt_hr=mrt,
            cl_int_mic_scaled_ml_min_kg=cl_int_mic_scaled,
            cl_int_hep_scaled_ml_min_kg=cl_int_hep_scaled,
            cl_hepatic_ml_min_kg=cl_h,
            extraction_ratio_eh=eh,
            extraction_class=eh_class,
            f_max_oral=f_max,
        )
